// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYL0bb6TSGQ6I0jRniDk6ETHvBZYVJ5P0',
    appId: '1:952360719783:web:71d6d64e72c4f6ddd55282',
    messagingSenderId: '952360719783',
    projectId: 'rate-2a422',
    authDomain: 'rate-2a422.firebaseapp.com',
    databaseURL: 'https://rate-2a422-default-rtdb.firebaseio.com',
    storageBucket: 'rate-2a422.appspot.com',
    measurementId: 'G-BFDVD5JLVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXDZUuXAR1paAOvE3jO-TQAhTOc1n5R6U',
    appId: '1:952360719783:android:11adb711b8863b6ed55282',
    messagingSenderId: '952360719783',
    projectId: 'rate-2a422',
    databaseURL: 'https://rate-2a422-default-rtdb.firebaseio.com',
    storageBucket: 'rate-2a422.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1RBXUPb_8ozmQwd4gAE01NpMu_r7LO5k',
    appId: '1:952360719783:ios:31952c0092dcd439d55282',
    messagingSenderId: '952360719783',
    projectId: 'rate-2a422',
    databaseURL: 'https://rate-2a422-default-rtdb.firebaseio.com',
    storageBucket: 'rate-2a422.appspot.com',
    iosBundleId: 'com.example.appdanhgia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1RBXUPb_8ozmQwd4gAE01NpMu_r7LO5k',
    appId: '1:952360719783:ios:fe920b0ba62a68abd55282',
    messagingSenderId: '952360719783',
    projectId: 'rate-2a422',
    databaseURL: 'https://rate-2a422-default-rtdb.firebaseio.com',
    storageBucket: 'rate-2a422.appspot.com',
    iosBundleId: 'com.example.appdanhgia.RunnerTests',
  );
}
